ca

diff --git a/backend/.github/workflows/cicd.yml b/backend/.github/workflows/cicd.yml
--- a/backend/.github/workflows/cicd.yml
+++ b/backend/.github/workflows/cicd.yml
@@ -1,6 +1,7 @@
 name: Deploy wordaday-backend
+
 on: 
-  pull_request:
+  push:
     branches:
       - main
 
@@ -10,24 +11,27 @@ jobs:
     steps:
       - name: Checkout Source
         uses: actions/checkout@v4
-      - name: Login to docker hub
-        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}     
+
+      - name: Login to Docker Hub
+        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
+
       - name: Build Docker Image
-        run: docker build -t matt1128jr/wordaday-backend
-      - name: Publish Image to docker hub
+        run: docker build -t matt1128jr/wordaday-backend .
+
+      - name: Publish Image to Docker Hub
         run: docker push matt1128jr/wordaday-backend:latest
- 
- 
+
   deploy:
     needs: build
-    runs-on: self-hosted 
+    runs-on: self-hosted
     steps:
-      - name: Pull image from docker hub
+      - name: Pull image from Docker Hub
         run: docker pull matt1128jr/wordaday-backend:latest
+
       - name: Delete old container
-        run: docker rm -f wordaday-backend-container
+        run: docker rm -f wordaday-backend-container || true  # This ensures it doesn't fail if the container doesn't exist
+
       - name: Run Docker Container
-        run: docker run -d -p 5555:5555 --name wordaday-backend-container -e MONGO_PASSWORD='${{ secrets.MONGO_PASSWORD }}' matt1128jr/wordaday-backend
         run: |
           docker run -d -p ${{ secrets.PORT }}:${{ secrets.PORT }} \
           --name wordaday-backend-container \
